spring.application.name=ms-auth
server.port=7081
spring.data.mongodb.uri: mongodb://localhost:27017/authdb

# JWT configuration
jwt.secret: myVerySecretKeyForJwtAuthentication123456789

# 1 hour in milliseconds
jwt.expiration: 3600000